version: '2'
services:
  mariadb:
    image: mariadb:10.3
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=W2qgpsLtQt
    volumes:
    - /data/xlpsystem/mariadb/:/var/lib/mysql
  mediawiki:
    image: daocloud.io/weimar/xlp_mediawiki:20180827140844
    restart: always
    ports:
    - 801:80
    volumes:
    - /data/xlpsystem/mediawiki:/xlp_data
    - /data/xlpsystem/mediawiki_dev:/xlp_dev
    depends_on:
    - mariadb
    - matomo
    - elasticsearch
  wordpress:
    image: daocloud.io/weimar/xlp_wordpress:20180820185725
    restart: always
    environment:
    - WORDPRESS_DB_HOST=mariadb
    - WORDPRESS_DB_PASSWORD=W2qgpsLtQt
    ports:
    - 81:80
    volumes:
    - /data/xlpsystem/wordpress:/var/www/html
    depends_on:
    - mariadb
    - matomo
  matomo:
    image: daocloud.io/weimar/xlp_matomo:20180820163542
    restart: always
    ports:
    - 82:80
    volumes:
    - /data/xlpsystem/matomo:/var/www/html
    depends_on:
    - mariadb
  elasticsearch:
    image: daocloud.io/weimar/xlp_elasticsearch:20180822142218
    ports:
    - 9200:9200
    - 9300:9300
    volumes:
    - /data/xlpsystem/elasticsearch:/usr/share/elasticsearch/data
    environment:
    - discovery.type=single-node
    - bootstrap.memory_lock=true
    - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
  kibana:
    image: daocloud.io/weimar/xlp_kibana:20180821233221
    ports:
    - 5601:5601
    depends_on:
    - elasticsearch
